server:
  port: 8081

spring:
  application:
    name: financial-analytics-data-ingestion

clickhouse:
  url: jdbc:clickhouse://localhost:8123/financial_data
  username: default
  password: ""

ingestion:
  symbols: AAPL,GOOGL,MSFT,AMZN,TSLA,META,NVDA,NFLX
  history:
    days: 30
  schedule:
    # Daily update at 6 PM (after market close)
    daily:
      cron: "0 0 18 * * ?"
      enabled: true
    # Intraday updates every 15 minutes during market hours (9:30 AM - 4:00 PM EST)
    intraday:
      cron: "0 */15 9-16 * * MON-FRI"
      enabled: true
  retry:
    maxAttempts: 3
    backoffDelay: 2000  # milliseconds
    maxBackoffDelay: 10000  # milliseconds
    multiplier: 2.0
  alert:
    enabled: true
    threshold: 3  # Number of consecutive failures before alert

logging:
  level:
    com.financial.analytics: INFO
    yahoofinance: WARN
